### ISSUE TITLE
Application error on test connection

### ISSUE THREAD

**Issue by ujovlado** [keboola/db-extractor-mysql#59]
```
 Failed to connect!
Contact support@keboola.com and attach this exception id. docker-3ddc9cc9ddeb5d30e5198f0d81729221
```

**Comment by ujovlado** [comment]
![screenshot_2018-09-06_16-00-24](https://user-images.githubusercontent.com/419849/45162334-03ddcb00-b1ee-11e8-8002-a471a1949475.png)

**Comment by pivnicek** [comment]
@ujovlado Did this just start on 3.2.0?

**Comment by ujovlado** [comment]
```
root@d4021cba9d74:/code# php src/run.php --data=./data
[2018-09-06 14:13:26] CRITICAL: ErrorException:Undefined index: name {"errFile":"/code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php","errLine":105,"errCode":0,"errTrace":"#0 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(105): Keboola\\DbExtractor\\Application::Keboola\\DbExtractor\\{closure}(8, 'Undefined index...', '/code/vendor/ke...', 105, Array)\n#1 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(134): Keboola\\DbExtractor\\Application->validateTableParameters(Array)\n#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(53): Keboola\\DbExtractor\\Application->validateParameters(Array)\n#3 /code/src/run.php(63): Keboola\\DbExtractor\\Application->run()\n#4 {main}","errPrevious":""} []
```

**Comment by ujovlado** [comment]
probably bug in db-ext common

**Comment by pivnicek** [comment]
I'm going to revert that mysql release.  thanks ujo

**Comment by ujovlado** [comment]
wait a sec.

**Comment by ujovlado** [comment]
Ok, this is confusing.

It's on both sides. :)

**Comment by ujovlado** [comment]
This works:

```json
{
  "action": "testConnection",
  "parameters": {
    "db": {
      "host": "xxx",
      "user": "test",
      "password": "test",
      "database": "test",
      "port": 33306
    },
    "tables": []
  }
}

```

**Comment by ujovlado** [comment]
So, if we don't want to accept `testConnection` w/o `tables`, this issue can be closed.

**Comment by pivnicek** [comment]
Yes, but for config rows we're not adding `tables` (that's why mysql fails, but do to db-common teradata does not)

**Comment by pivnicek** [comment]
No, we want to accept testConnection and getTables without tables.  This is correctly a bug.
